# Site settings
title: "Ronen Amos - Technological Accounting Solutions"
description: "Professional accounting services with cutting-edge technology integration. Specializing in digital transformation for businesses in Israel."
baseurl: "/amos-financial-Solutions"
url: "https://ronenamos-arch.github.io"
author:
  name: "Ronen Amos"
  email: "info@amosfinancial.com"
  phone: "+972-50-123-4567"

# SEO settings
lang: he
locale: he_IL
alternate_locales: 
  - en_US
  - he_IL

# Business information for structured data
business:
  name: "Amos Financial Solutions"
  legal_name: "רונן עמוס - פתרונות חשבונאיים טכנולוגיים"
  description: "חשבונאי טכנולוגי מוביל בישראל. מתמחה בשירותי חשבונאות מתקדמים, דיגיטציה עסקית ויעוץ פיננסי."
  address:
    street: "רחוב הטכנולוגיה 123"
    city: "תל אביב"
    region: "מרכז"
    postal_code: "1234567"
    country: "IL"
  geo:
    latitude: "32.0853"
    longitude: "34.7818"
  contact:
    phone: "+972-50-123-4567"
    email: "info@amosfinancial.com"
    whatsapp: "+972501234567"
  hours:
    - days: "Sunday-Thursday"
      opens: "08:00"
      closes: "18:00"
    - days: "Friday"
      opens: "08:00" 
      closes: "13:00"
  services:
    - "Technological Accounting"
    - "Digital Business Transformation"
    - "Financial Consulting"
    - "Tax Planning"
    - "Bookkeeping Automation"
    - "ERP Implementation"

# Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Include files
include:
  - _pages

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

# Social media
social:
  linkedin: "https://linkedin.com/in/ronen-amos"
  twitter: "@ronenamos"
  facebook: "AmosFinancialSolutions"

# Google services
google_analytics: "G-XXXXXXXXXX"
google_site_verification: "your-verification-code"

# Site verification
webmaster_verifications:
  google: your-google-verification-code
  bing: your-bing-verification-code